### ISSUE TITLE
Supposed to work in later version of VS Code?

### ISSUE THREAD

**Issue by micceo** [m417z/vscode-regedit#1]
This would be an awesome extension if I can get it to work. Is it supposed to work in current version of VS Code?
I don't see the menu addition "New regedit Tab".

Version: 1.86.2 (system setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by m417z** [comment]
Works for me in the exact same version.

![Code_wpn276k2CE](https://github.com/m417z/vscode-regedit/assets/4129781/73ccba49-23f2-4aa1-bacb-8ceaf28f8b91)

**Comment by micceo** [comment]
Hi!

My bad! I though I read up on this one, but totally missed where to add the tab for it to show.

Brgs, micce, and many thanks for chipin' with the information.

 neomo ab · Mikael Östergren · ***@***.*** · +46 70 555 44 31 · https://neomo.se · 💻
